### ISSUE TITLE
Support for symfony 3.4

### ISSUE THREAD

**Issue by boudewijn-zicht** [thecodingmachine/graphqlite#119]
We would like to use graphqlite but unfortunately we are still stuck on symfony 3.4.  Are there plans to make graphqlite backwards compatible with symfony 3.4?

**Comment by moufmouf** [comment]
Hey @boudewijn-zicht ,

We have no plan to work on a Symfony 3.4 bundle so far. That being said, I don't think it would be too difficult to add support in Symfony 3.4 since I don't believe we are using features specific to Symfony 4.1+ (except in the tests)

If you are willing to have a look and work on a PR, I can happily merge it. https://github.com/thecodingmachine/graphqlite-bundle

**Comment by boudewijn-zicht** [comment]
The conflict seems to be in the graphqlite library itself

https://github.com/thecodingmachine/graphqlite/commit/1cf62b84a21019721fc2f1445a5ce6c11ad0aa0a

The above commit introduced a requirement on "symfony/cache": "^4.3", the cache contracts that are now used do not appear to exist in symfony 3.

My assumption is that this makes it quite hard to make it compatible with symfony 3... but perhaps I am wrong?

**Comment by moufmouf** [comment]
Ho.... you are absolutely right. Sorry, I forgot this dependency. We are using the new Symfony cache contracts, and they are indeed absolutely needed.
Reimplementing those in our code in order to be able to downgrade to Symfony cache ^3||^4 would indeed need a considerable amount of work.

Sorry about that.
