### ISSUE TITLE
How to set SchemaFactory without a framework ?

### ISSUE THREAD

**Issue by jmurrayrs** [thecodingmachine/graphqlite#120]
Hello! I would like to create an implementation of GraphQL using the facilities of GraphQL Lite.  Reading the documentation I can create a service without any framework. At this point, it's perfect! But I've had problems when I want to create an instance of SchemaFactory,because the construct need two instances: a $cache where the variable needs to be a PSR-16 compatible cache and $container  where the variable needs to be a PSR-11 compatible container.

So, how can I create it ? could you help me ?

Thanks!

**Comment by moufmouf** [comment]
Hey @jmurrayrs ,

GraphQLite needs indeed a PSR-16 compatible cache and a PSR-11 compatible container to run.
You are not using any framework right?

So you can pick any implementation compatible with PSR-16 and PSR-11 (on packagist, using Composer)

For instance, the "symfony/cache" package provides different cache mechanism that implement PSR-16.
If you are looking for a PSR-11 container, have a quick look [at the different containers available that implement PSR-11](https://packagist.org/providers/psr/container-implementation)
I highly recommand you pick one with the autowiring feature since it makes using GraphQLite way easier.

**Comment by jmurrayrs** [comment]
Hello @moufmouf ! Thank you very much for your help. I'll try to do it. See you !

**Comment by Purus** [comment]
I could not find any simple example which uses some cache and container.. Am I missing anything? Please let me know.. I am not getting my code to work with any PSR-11 container.. any code sample would help.
