### ISSUE TITLE
Requested fields for a type?

### ISSUE THREAD

**Issue by crirus** [thecodingmachine/graphqlite#121]
Hello

Is there any way to read the requested fields for certain type?
For example I have a Product with many fields (brand, category, name, id)  but client only wants the name. Can I get that in resolver or a dependency that offers it?

**Comment by jmurrayrs** [comment]
Hello crirus! For example, we have this Query

Products (id:20) {
  Price,
  Name,
 BrandName
}

If you Want only name:

Products (id:20) { 
  Name 
}

The Customer/Client will choose what to return by the Query. The Application, in the resolver, must populate with data from Database/File, etc

**Comment by moufmouf** [comment]
Hey @Crirus!

@jmurrayrs answer is correct. The whole purpose of GraphQL is to let you fetch exactly the fields you need. If this is not obvious to you, maybe you can take a look at [the main GraphQL tutorial](https://graphql.org/learn).

Now, I feel that you already know that and that your question is rather: "is there a way to get in advance the list of fields that I will have to resolve"?
And I also guess you are asking because your backend is a database and you would like to fetch only the columns that will be needed instead of fetching all the columns? Am I correct?

If this is what you are trying to do, we added in GraphQLite 4 a new way to access the GraphQL request.
GraphQLite is built on top of the webonyx/graphql-php. This library comes with a "ResolveInfo" object that contains information related to the requested fields.

You can now type-hint on `ResolveInfo` in any resolver.

See documentation here: 

https://graphqlite.thecodingmachine.io/docs/next/query-plan

Please note this is only available in GraphQLite 4. It is not yet tagged stable but will be in less than a month, and I don't expect any more breaking changes, so you can start using GraphQLite 4 right now.
