### ISSUE TITLE
"Use your beans as input types" doesn't work on Symfony

### ISSUE THREAD

**Issue by ThibBal** [thecodingmachine/graphqlite#148]
Stack: Symfony 4 - TDBM5 - GraphQLite

Situation: I have an AdminUser bean, an AdminUserDAO (with the Factory annotation). I want to inject into my mutation the AdminUser automatically.

`public function saveAdmin(?AdminUser $adminUser, string $lastname, string $firstname, string $email, ?string $login, ?string $phone, ?string $password, string $status, string $role, string $pole): AdminUser`

Error : I have an error :

> In DefinitionErrorExceptionPass.php line 54:
> 
>   Cannot autowire service "App\Model\AdminUser": argument "$email" of method "App\Model\Generated\AbstractAdminUser::
>   __construct()" is type-hinted "string", you should configure its value explicitly.

**Comment by moufmouf** [comment]
After looking at the problem, the issue is linked to Symfony's argument autowiring.

If your GraphQL controller class is tagged with "controller.service_arguments", Symfony will try to autowire the argument automatically (even if it is not annotated with @AutoWire).

The "controller.service_arguments" tag is put on any class that:

- is part of "App\Controller" directory
- OR extends the AbstractController class

We need to fix the documentation and the GraphQLite Symfony bundle to be sure that the default values we propose for the GraphQL controllers are NOT in App\Controller.
