### ISSUE TITLE
Laravel relationship not working

### ISSUE THREAD

**Issue by XPOL555** [thecodingmachine/graphqlite#162]
When Declaring a model with an hasMany 

```php
<?php

class Company extends Model{
    /**
     * @Field()
     * @return Address[]|HasMany
     */
    public function addresses():array {
        return $this->hasMany('App\Address');
    }
}
```

I got this message:

```
  "message": "Return value of App\\Company::addresses() must be of the type array, object returned",
  "exception": "Symfony\\Component\\Debug\\Exception\\FatalThrowableError",

```

is this intended? I expect to directly query the related model

NB: i'm using v4 dev-master on laravel 6

**Comment by moufmouf** [comment]
Hey @XPOL555 ,

What you describe is logic.

`$this->hasMany('App\Address');` returns a "HasMany" object that is not "traversable".
When you want to go through your collection, you call "$this->addresses", not "$this->addresses()".

So GraphQLite needs to target the magic property and not the method. Since GraphQLite has no way to target a magic property (I'm working to improve that), you need instead to apply the @Field annotation on a getter that wraps the property. So here is what you want to do:

```php
class Company extends Model{
    public function addresses() {
        return $this->hasMany('App\Address');
    }

    /**
     * @Field()
     * @return Address[]
     */
    public function getAddresses():iterable {
        return $this->addresses;
    }

}
```

Let me know, this should work.

**Comment by XPOL555** [comment]
Thank you @moufmouf for the quick reply and... yess! It works like magic! Thank you so much.

I also changed to a `belongsToMany` with a pivot table and still works.

**Comment by XPOL555** [comment]
@moufmouf just migrated from dev to v4 and had no issues - great work guys!
