### ISSUE TITLE
Architecture basics for usage -- is this useful for me at all?

### ISSUE THREAD

**Issue by hlu67** [thecodingmachine/graphqlite#184]
Hi! Just found GraphQL idea at large, and headed to evaluate GraphQLite right away. I'm refactoring an 15-year old PHP app, created with no framework other than Smarty. OO approach used, fortunately. Have converted it to PHP7, comfortable at running it on standard LAMP-based commercial webhost. Aiming to modernize some of the UI. Played some proof-of-concept with XML-RPC at 2007. Thats severely deprecated in PHP now. Now I consider skipping REST and heading right to GraphQL. Already did convert my app to use PHP namespace, to conform with GraphQLite requirements. OK, nice move, will keep it anyway. SchemaFactory? Cache? Smarty has one, I doubt that counts? Container? Now I'm stuck, not willing to use containers at any time soon with this project. So, I guess it's no GraphQLite kickstart for me with SchemaFactory? Is GraphQLite right tool for me at all? Any pointers to how I should bring selected methods from my code available for GraphQL queries using GraphQLite facilities? Am I better learning to do that hard way with vanilla  webonyx/graphql-php?

**Comment by moufmouf** [comment]
Hey @hlu67 ,

Your best chance with GraphQLite is to use the `SchemaFactory`. It requires a cache and a container because classes underneath require it anyway. I would strongly advise you against bypassing `SchemaFactory`.

GraphQLite needs a container in order to instantiate the controllers (the classes in which you will put the "@Query" annotations).
Adding a container can actually be quite easy. I would try using a DI container with autowiring capabilities. That way, you don't have to do anything particular regarding configuration.

For instance, you could use PHP-DI: http://php-di.org/doc/container-configuration.html

Instantiating the container is as easy as:

```php
$container = new Container();
```

Then, you need a PSR-16 compatible cache. Anything from this list should work: https://packagist.org/providers/psr/simple-cache-implementation

> Is GraphQLite right tool for me at all?

If you have a project with Composer, PSR-4 autoloading, namespaces and classes, this should be a match for GraphQLite. The time you spend setting up the container will be nothing compared to the time you will save from doing things the hard way with Webonyx (I think :) )

**Comment by hlu67** [comment]
Thank you moufmouf, 
It seems I need to do some learning with that container stuff to make an informed decision about this.  Will look at PHP-DI demo app to get better understanding about it. Thanks for pointing out PHP-DI!
