### ISSUE TITLE
Controller discovery too eager

### ISSUE THREAD

**Issue by NekiCat** [thecodingmachine/graphqlite#207]
I have a project in which I use *PHP-DI* as a container. I have problems with the following project structure:
```
\ControllerNamespace\SpecificController\MyController
\ControllerNamespace\SpecificController\Model\MyControllerSpecificModelClasses
```
I have set `ControllerNamespace\` as the controller namespace to recursively discover all my controllers (which works great), but my model classes are also discovered.

Then *GraphQLite* tries to get the model classes from the container. *PHP-DI* finds them and tries to construct them, but the model classes are not meant to be injected/constructed this way. They take some scalar types in their constructor, which *PHP-DI* cannot resolve, resulting in an exception.

Would it be possible to scan the classes *before* constructing them, to make sure they actually are relevant? Alternatively, would it be possible to restrict discovery to maybe class names ending in `Controller` with a user-defined filter?

**Comment by oojacoboo** [comment]
Why is your model in your controller namespace?  That seems like a really abnormal way of organizing things.

**Comment by NekiCat** [comment]
I tried to group classes by what they are for, not what they are. That way, when I'm working on the user api for example, I don't have to jump all over the project and look through models that are for completely different parts of the program. I have all the classes concerning the user api right there in the same folder.

**Comment by oojacoboo** [comment]
IMO, that logic, while seemingly well intentioned, is flawed.  Your domain model should never be coupled with your controller layer.  Your domain model is also likely to be used for other services and layers within an application.

**Comment by moufmouf** [comment]
@oojacoboo The approach taken by @NekiCat is not uncommon. See https://mnapoli.fr/organizing-code-into-domain-modules/

@NekiCat your issue is valid, I could indeed restrict the instantiated classes to those containing a @Query or @Mutation annotation.
I'll look into it.

**Comment by oojacoboo** [comment]
@moufmouf I'm not sure I'd extend feature organization to models in the controller namespace.  In the feature organization which makes total sense, I'd still argue that you should have sub directories within each feature.  So, you'd have a "Controller" and "Model" dir, for instance.

That said, that still wouldn't address the issue here.  However, would could address this issue, is that if the namespace setter for the config, used the glob syntax.  Ultimately, this would allow much more flexibility and also possibly add a performance boost from decreasing the read/scan time for annotations across unnecessary files.  Thoughts?

**Comment by moufmouf** [comment]
> I'd still argue that you should have sub directories within each feature. So, you'd have a "Controller" and "Model" dir, for instance.

Agreed.
But the issue faced by @NekiCat could be faced by someone else with a perfectly well organized code. The fact that GraphQLite will try to instantiate classes that do not contain "@Query" or "@Mutation" annotated methods is a problem (+ it is bad for performance), so I'll still try fix this issue.

> However, what could address this issue, is that if the namespace setter for the config, supported the glob syntax.

That would indeed be a great addition. It would require quite some work however, since indeed, we would need to support the glob syntax for namespaces. That would require to rewrite the `GlobClassExplorer` class in this package: https://github.com/thecodingmachine/class-explorer
