### ISSUE TITLE
Dependency  "ocramius/package-versions": "^1.4" breaking php version requirements in 4.0.3

### ISSUE THREAD

**Issue by oneserv-heuser** [thecodingmachine/graphqlite#295]
The dependency "ocramius/package-versions": "^1.4" introduces a bug with PHP 7.3 and 7.2. The package  "ocramius/package-versions" added PHP 7.4 as minimum required version in its 1.6 release. It's also using the new feature typed properties which results in 
``
PHP Parse error:  syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in ...../vendor/ocramius/package-versions/src/PackageVersions/Installer.php on line 34
``

Unfortantly the 1.6.0 release of the package was not a major version change which should have been made as it's not backwards compatible. To keep the requirement of "php": ">=7.2" valid "ocramius/package-versions" must be constraint to be 1.5 as maximum.

**Comment by moufmouf** [comment]
Hey @oneserv-heuser 

> Unfortantly the 1.6.0 release of the package was not a major version change which should have been made as it's not backwards compatible.

Actually, @ocramius can bump the minimum required PHP version in a minor version of its package. This is OK because when you run `composer update`, Composer will never install a package that is not compatible with your version of PHP. The Composer solver will take care of this for you.

See https://www.doctrine-project.org/2017/07/25/php-7.1-requirement-and-composer.html

If you are having this issue, it is either that:

- you are running `composer update` on a dev machine that does not have the same PHP version as your production environment. In this case, I would recommend either to use Docker or to enforce the PHP version in your composer.json (see https://andy-carter.com/blog/composer-php-platform)
- you are using the `--ignore-platform-reqs` flag in Composer (which you should definitely avoid)

> To keep the requirement of "php": ">=7.2" valid "ocramius/package-versions" must be constraint to be 1.5 as maximum.

This would actually introduce a lot of problems. Other packages having the same dependency could target other versions of this package. If another package has a dependency on ocramius/package-versions:^1.6, we would not be able to install it. That would introduce useless conflicts with other packages (which we definitely want to avoid!)

**Comment by oneserv-heuser** [comment]
@moufmouf Well, must've been a weird bug then. Anyway, thanks for your reply!
