### ISSUE TITLE
No caching of doctrine annotations, since its set to debug mode

### ISSUE THREAD

**Issue by rlweb** [thecodingmachine/graphqlite#357]
https://github.com/thecodingmachine/graphqlite/blob/6b077e60fdef3ce53db3639de78d7d40fbb8f5d8/src/SchemaFactory.php#L236

This might only be for non-framework applications but the debug mode here is set to true therefore bypassing the annotation cache!

I was thinking to make ->prodMode set a flag, and for that flag to be used to disable debug mode for doctrine annotation cache. Thoughts?

**Comment by oojacoboo** [comment]
@rlweb You could use the `setDoctrineAnnotationReader` method to explicitly set the annotation reader.  This would allow you to specify the debug mode you desire.

That said, I'm not quite sure what the logic is here, or if this is an oversight.  Unfortunately, we cannot rely on the `prodMode` method as that's really just an alias method to the `setGlobTTL`.  Therefore, there isn't a dev/prod state being maintained.

Have you done any (performance) testing with debug mode enabled/disabled here?

It looks like the proper fix here is going to be a new property/state to maintain the env, defaulting to dev since that's already the default with the `globTTL` and we'd want to maintain BC here.  Then, we could rely on that property/state to determine the debug mode for the cache reader.

**Comment by oojacoboo** [comment]
At this point, please consider moving away from Doctrine annotation to native PHP attributes.
