### ISSUE TITLE
Native Enums Support

### ISSUE THREAD

**Issue by enumag** [thecodingmachine/graphqlite#407]
From the [documentation](https://graphqlite.thecodingmachine.io/docs/type-mapping#enum-types) I can see that this library supports myclabs/php-enum.

The upcoming PHP 8.1 will however have native enums. Are native enums supported as well? If not is there a plan to add the support? I'd like to move away from using myclabs enums if possible.

**Comment by oojacoboo** [comment]
Native enums aren't currently supported.  However, a PR adding support for 8.1 will be happily accepted.  Support for `myclabs/php-enum` will need to remain in place and deprecated until PHP 8.1 has a high enough use percentage.

**Comment by enumag** [comment]
Do you have some estimate of the scope? What would the PR need to implement? Would be helpful if someone wants to try and send such PR. Not saying I'll try. It's possible but can't promise it yet.

**Comment by oojacoboo** [comment]
I'm not familiar with the Enum portion of the lib, but you'd basically just have to translate an Enum to a GraphQL enum type instead of the enum lib.  The lib would need to support both, so you'd just add an additional type translation, basically.

It's probably about 3-4 hours of coding work to get looking good and maybe another hour to get the PR wrapped up.

**Comment by Lappihuan** [comment]
@oojacoboo this can be closed since the PR is merged
