### ISSUE TITLE
Rector's `AnnotationToAttribute` and `UseInputType` incompatibilities

### ISSUE THREAD

**Issue by smilesrg** [thecodingmachine/graphqlite#478]
I'm not sure if it's a question to Rector or GraphQLite, but:

```
Attribute "TheCodingMachine\GraphQLite\Annotations\UseInputType" cannot target method (allowed targets: parameter)
```

**Comment by oojacoboo** [comment]
Can you please provide a code example of the `UseInputType` annotation?

**Comment by smilesrg** [comment]
```php
    /**
     * @UseInputType(for="$foo", inputType="Foo!")
     */
    public function fooBar(string $foo): Bar
    {
    }
```

**Comment by oojacoboo** [comment]
This makes sense.  Rector is going to apply that as an attribute on the method and not the parameter, since it doesn’t know.  You’ll probably have to modify the Rector rule to create a custom one, or manually modify the generated attributes.

Attributes for parameters are applied in the method signature, directly before the param.
