### ISSUE TITLE
Parameter is missing for class constructor for boolean properties

### ISSUE THREAD

**Issue by ozahorulia** [thecodingmachine/graphqlite#481]
**Input class:**

```
#[Input]
class SomeInput
{
    public function __construct(
        #[Field(inputType: 'Boolean!')]
        public readonly bool $x,

        #[Field(inputType: 'Boolean!')]
        public readonly bool $y,
    ) {
    }
}
```

**Mutation:**
```
mutation {
  updateSomething(someInput:
    {
      x: false
      y: false
    }
  )
}
```

**Result:**
```
"Parameter 'x' is missing for class 'SomeInput' constructor. It should be mapped as required field."
```

If I change type to any other (e.g. string) - it works. If I pass true instead of false as **x** or **y** argument - it also works.
Looks like problem occurs for boolean fields with false values.

**Comment by oojacoboo** [comment]
@ozahorulia yea, this is very likely.  Are you using `master`?  Also, what's your `Type` annotation look like?  There have been some recent improvements for Input types with a new "update" option.

**Comment by ozahorulia** [comment]
The project is in production, so not master, bust last available version (5.0.2).

My Type class looks like this:

```
#[Type(class: SomeClass::class)]
#[SourceField(name: 'x')]
#[SourceField(name: 'y')]
class SomeClass
{
}
```

And the referenced `SomeClass` itself of course has `getX(): bool` and `getY(): bool` methods.

**Comment by oojacoboo** [comment]
That's understandable @ozahorulia.  We should have a new update released soon, 6.0.  You'll likely need to wait until that happens before this issue is resolved.  However, in the meantime, you might test `master` to see if it resolves your issue, so that we can proceed towards a PR, otherwise.

As you can see in the [docs here](https://graphqlite.thecodingmachine.io/docs/next/annotations-reference#input) there is a new `update` option for `Input` type annotations.  This denotes the `Input` as an update action, and alters the behavior of nullable fields.  I suspect that `false` would be evaluated properly under an "update" `Input` type.

**Comment by ozahorulia** [comment]
As for Type annotation - I have no problems with that, it works just as expected. It's separated from the referenced class just in order to separate models, so it doesn't change anything in case of this issue.

I just tried `#[Input(update: true)]` option, as it exists in `5.0.2`. Unfortunately it does not change anything for me. But it's very clear that the problem appears only if properties are promoted in the constructor.

If I declare it like this, everything works perfectly:

```
#[Input]
class SomeInput
{
    #[Field(inputType: 'Boolean!')]
    public bool $x,

    #[Field(inputType: 'Boolean!')]
    public readonly bool $y,
}
```

**Comment by ozahorulia** [comment]
For me it looks pretty similar to #410. Is it possible to merge #411 and tag it as 5.0.3 or something?

**Comment by oojacoboo** [comment]
@ozahorulia happy to get that merged in.  We need to get at least one test written for that though.  Could you help us out and push a test on the author's branch?
