### ISSUE TITLE
Enum types value incorrect

### ISSUE THREAD

**Issue by charles4201** [thecodingmachine/graphqlite#91]
as example shows from : https://graphqlite.thecodingmachine.io/docs/next/type_mapping
```
use MyCLabs\Enum\Enum;

class StatusEnum extends Enum
{
    private const ON = 'on';
    private const OFF = 'off';
    private const PENDING = 'pending';
}

```
```
/**
 * @Query
 * @return User[]
 */
public function users(StatusEnum $status): array
{
    if ($status === StatusEum::ON()) {
        // ...
    }
    // ...
}
```

The condition "$status === StatusEum::ON()" will always be false, since it's two different objects, with an unknow cache.

After I changed to this, it gets working : 
```
class StatusEnum extends Enum
{
    public const ON = 'on';
    public const OFF = 'off';
    public const PENDING = 'pending';
}
```

`if ($status->getValue()  === StatusEum::ON)`

**Comment by moufmouf** [comment]
Hey Nan,

You are perfectly right. I just reproduced the issue.

Actually, it seems to be an expected behaviour of MyCLabs/php-enum as each call to `StatusEum::ON()` will return a new instance of the object (that's a shame...)

Anyway, you can also fix this by replacing "===" with a simple "==" like this:

```php
/**
 * @Query
 * @return User[]
 */
public function users(StatusEnum $status): array
{
    if ($status == StatusEum::ON()) {
        // ...
    }
    // ...
}
```

I will fix GraphQLite documentation as it is wrong.
